services:
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/AutoReload.Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./API:/src/API
    networks:
      - app-network
  
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/AutoReload.Dockerfile
    ports:
      - "80:8081"
    volumes:
      - ./Frontend:/src/Frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  