services:

  auto-front:
    image: mud-blazor
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./Frontend:/src/Frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
