services:
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./API:/src/API
    networks:
      - app-network

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./Frontend:/src/Frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
