services:
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8000:8080"
    networks:
      - app-network

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
