services:

  auto-front:
    image: mud-blazor
    build:
      context: .
      dockerfile: MudBlazorWebApp1/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./MudBlazorWebApp1:/src/MudBlazorWebApp1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
